### ISSUE TITLE
FITAERO module not writing in inaero.dat file

### ISSUE THREAD

**Issue by theodorekhadir** [mafor2/mafor#3]
Hello,

When using the FITAERO fortran module, the program is not writing in the inaero.dat file.
I solved the issue by closing the file (the file was created/opened but not closed):
- in the *prog_fitaero.for* file
- I added: **close (funit_out_inaero)** below the line containing **close(funit_out_sizedis)**

Hope this helps,

Best regards,
Theodore

**Comment by mafor2** [comment]
Dear Theodore,

Thank you for reporting the issue. I followed your suggested change to close the inaero.dat file after writing.
There are also some other changes in FITAERO that I commited as version 1.1.

Best regards,
Matthias
